responsivewrappers.settings:
  type: config_object
  label: 'Responsive wrappers settings'
  mapping:
    add_css:
      type: integer
      label: 'Attach module CSS with input filter'
    version:
      type: integer
      label: 'Bootstrap output version'
