field.formatter.settings.shrinktheweb_link_default:
  type: mapping
  label: '[ShrinkTheWeb] Title as link format settings'
  mapping:
    custom_width:
      type: integer
      label: 'Custom Width'
    full_length:
      type: integer
      label: 'Full-Length capture'
    max_height:
      type: integer
      label: 'Max height'
    native_resolution:
      type: integer
      label: 'Native resolution'
    widescreen_resolution_y:
      type: integer
      label: 'Widescreen resolution Y'
    delay:
      type: integer
      label: 'Delay After Load'
    quality:
      type: integer
      label: 'Quality'

field.formatter.settings.shrinktheweb_link_plain:
  type: field.formatter.settings.shrinktheweb_link_default
  label: '[ShrinkTheWeb] URL as plain text'

field.formatter.settings.shrinktheweb_link_url:
  type: field.formatter.settings.shrinktheweb_link_default
  label: '[ShrinkTheWeb] URL as link'

field.formatter.settings.shrinktheweb_link_short:
  type: field.formatter.settings.shrinktheweb_link_default
  label: "[ShrinkTheWeb] Short as link with title 'Link'"

field.formatter.settings.shrinktheweb_link_separate:
  type: field.formatter.settings.shrinktheweb_link_default
  label: '[ShrinkTheWeb] Separate title and URL'

field.formatter.settings.shrinktheweb_link_no_text:
  type: field.formatter.settings.shrinktheweb_link_default
  label: '[ShrinkTheWeb] No link text'